### ISSUE TITLE
Local development 

### ISSUE THREAD

**Issue by ArifRasim** [hyus314/CS50-Finance#1]
Add a Readme for local development of the project

**Comment by hyus314** [comment]
on it.

**Comment by hyus314** [comment]
yooo burdan yazishmak cok bet

**Comment by hyus314** [comment]
[https://github.com/hyus314/CS50-Finance/commit/1ee54f6c7ffab7d89a0f68690de6141597acfafe](url)

**Comment by hyus314** [comment]
https://github.com/hyus314/CS50-Finance/commit/1ee54f6c7ffab7d89a0f68690de6141597acfafe
